version: '3'
services:
  front-end:
    restart: always
    build : ./front-end
    ports :
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./front-end:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  back-end:
    restart: always
    build : ./back-end/api
    ports :
      - '5050:5050'
    volumes:
      - ./back-end/api:/app