version: '3'
services:
  front-end:
    restart: always
    build : ./front-end
    ports :
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./front-end:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  back-end:
    restart: always
    build : ./back-end/api
    ports :
      - '5050:5050'
    volumes:
      - ./back-end/api:/app
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootUser
    volumes:
      - mangodb_data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootUser
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_URL: "mongodb://root:rootUser@mongo:27017/"
    depends_on:
      - mongo
volumes:
  mangodb_data: